# See usage of https://github.com/kubernetes/code-generator if regeneration of the following is required:
#       integrations/apis/flux.weave.works/*/zz_generated.deepcopy.go
#       integrations/client/*
#
required = ["k8s.io/code-generator/cmd/client-gen"]

[[override]]
  name = "github.com/ugorji/go"
  revision = "8c0409fcbb70099c748d71f714529204975f6c3f"

[[constraint]]
  name = "github.com/docker/distribution"
  branch = "master"
  source = "github.com/2opremio/distribution"

# Pin to master branch until there is a more recent stable release:
#   https://github.com/prometheus/client_golang/issues/375
[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "11.0.0"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.14"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[constraint]]
  name = "k8s.io/helm"
  version = "~v2.13.0"

[[constraint]]
  name = "github.com/2opremio/go-k8s-portforward"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/term"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "1.4.0"

[[override]]
  name = "github.com/BurntSushi/toml"
  version = "v0.3.1"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.7"
