# See usage of https://github.com/kubernetes/code-generator if regeneration of the following is required:
#       apis/integrations.flux/zz_generated.deepcopy.go
#       integrations/client/*
#
required = ["k8s.io/code-generator/cmd/client-gen"]

[[override]]
  name = "github.com/ugorji/go"
  revision = "8c0409fcbb70099c748d71f714529204975f6c3f"

[[constraint]]
  name = "github.com/docker/distribution"
  branch = "master"

# Pin to master branch until there is a more recent stable release:
#   https://github.com/prometheus/client_golang/issues/375
[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.11"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[constraint]]
  name = "k8s.io/helm"
  version = "v2.8.1"

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.2.0"

[[constraint]]
	name = "github.com/justinbarrick/go-k8s-portforward"
	version = "v1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/term"
