site_name: Flux
# site_description:
site_author: Flux Project
site_url: https://docs.fluxcd.io/

# Repository
repo_name: fluxcd/flux
repo_url: https://github.com/fluxcd/flux
edit_uri: ""

theme:
  name: material
  logo: _files/flux-icon@2x.png
  language: en
  feature:
    tabs: false
  palette:
    primary: blue
    accent: indigo

docs_dir: docs

extra_css:
  - _static/custom.css

plugins:
  - search
    #  - redirects:
    #  redirect_maps:
    #    'guides/upgrading-to-ga.md': 'how-to/upgrade-to-ga.md'
    #    'guides/upgrading-to-beta.md': 'how-to/upgrade-to-beta.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences

nav:
  - Introducing Flux: introduction.md
  - Requirements and limitations: requirements.md
  - Get Started: get-started/index.md
  - References:
    - Blueprint: references/blueprint.md
    - Daemon (fluxd): references/daemon.md
    - fluxctl: references/fluxctl.md
    - Manifest generation through .flux.yaml configuration files: references/fluxyaml-config-files.md
    - Garbage collection: references/garbagecollection.md
    - Git commit signing and verification: references/git-gpg.md
    - Automated deployment of new container images: references/automated-image-update.md
    - Integration with the Helm operator: references/helm-operator-integration.md
    - Monitoring Flux: references/monitoring.md
  - Guides:
    - Providing your own SSH key: guides/provide-own-ssh-key.md
    - Using Git over HTTPS: guides/use-git-https.md
    - Using a private Git host: guides/use-private-git-host.md
    - Upgrading to Flux v1: guides/upgrading-to-1.0.md
  - Tutorials:
    - Get started: tutorials/get-started.md
    - Get started using Helm: tutorials/get-started-helm.md
    - How to bootstrap Flux using Kustomize: tutorials/get-started-kustomize.md
    - Automations, locks and annotations: tutorials/driving-flux.md
  - Frequently asked questions: faq.md
  - Troubleshooting: troubleshooting.md
  - Contributing:
    - Get started developing: contributing/get-started-developing.md
    - Building Flux: contributing/building.md

