{{- $gitTimeout := default .Values.git.timeout .Values.helmOperator.git.timeout }}
{{- if .Values.helmOperator.create -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "flux.fullname" . }}-helm-operator
  labels:
    app: {{ template "flux.name" . }}-helm-operator
    chart: {{ template "flux.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.helmOperator.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "flux.name" . }}-helm-operator
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.prometheus.enabled }}
      annotations:
        prometheus.io.scrape: "true"
      {{- end }}
      labels:
        app: {{ template "flux.name" . }}-helm-operator
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "flux.serviceAccountName" . }}
      volumes:
      {{- if .Values.ssh.known_hosts }}
      - name: sshdir
        configMap:
          name: {{ template "flux.fullname" . }}-ssh-config
          defaultMode: 0600
      {{- end }}
      - name: git-key
        secret:
          {{- if .Values.helmOperator.git.secretName }}
          secretName: {{ .Values.helmOperator.git.secretName }}
          {{- else if .Values.git.secretName }}
          secretName: {{ .Values.git.secretName }}
          {{- else }}
          secretName: {{ template "flux.fullname" . }}-git-deploy
          {{- end }}
          defaultMode: 0400
      {{- if .Values.helmOperator.tls.enable }}
      - name: helm-tls-certs
        secret:
          secretName: {{ .Values.helmOperator.tls.secretName }}
          defaultMode: 0400
      {{- if .Values.helmOperator.tls.verify }}
      - name: helm-tls-ca
        configMap:
          name: {{ template "flux.fullname" . }}-helm-tls-ca-config
          defaultMode: 0600
      {{- end }}
      {{- end }}
      {{- if .Values.helmOperator.configureRepositories.enable }}
      - name: {{ .Values.helmOperator.configureRepositories.volumeName | quote }}
        secret:
          secretName: {{ .Values.helmOperator.configureRepositories.secretName | quote }}
      - name: {{ .Values.helmOperator.configureRepositories.cacheVolumeName | quote }}
        emptyDir: {}
      {{- end }}
      containers:
      - name: flux-helm-operator
        image: "{{ .Values.helmOperator.repository }}:{{ .Values.helmOperator.tag }}"
        imagePullPolicy: {{ .Values.helmOperator.pullPolicy }}
        ports:
        - name: http
          containerPort: 3030
        volumeMounts:
        {{- if .Values.ssh.known_hosts }}
        - name: sshdir
          mountPath: /root/.ssh/known_hosts
          subPath: known_hosts
          readOnly: true
        {{- end }}
        - name: git-key
          mountPath: /etc/fluxd/ssh
          readOnly: true
        {{- if .Values.helmOperator.tls.enable }}
        - name: helm-tls-certs
          mountPath: /etc/fluxd/helm
          readOnly: true
        {{- if .Values.helmOperator.tls.verify }}
        - name: helm-tls-ca
          mountPath: /etc/fluxd/helm-ca
          readOnly: true
        {{- end }}
        {{- end }}
        {{- if .Values.helmOperator.configureRepositories.enable }}
        - name: {{ .Values.helmOperator.configureRepositories.volumeName | quote }}
          mountPath: /var/fluxd/helm/repository
        - name: {{ .Values.helmOperator.configureRepositories.cacheVolumeName | quote }}
          mountPath: /var/fluxd/helm/repository/cache
        {{- end }}
        args:
        - --git-timeout={{ $gitTimeout }}
        - --charts-sync-interval={{ .Values.helmOperator.chartsSyncInterval }}
        - --update-chart-deps={{ .Values.helmOperator.updateChartDeps }}
        - --log-release-diffs={{ .Values.helmOperator.logReleaseDiffs }}
        {{- if .Values.helmOperator.namespace }}
        - --allow-namespace={{ .Values.helmOperator.allowNamespace }}
        {{- end }}
        - --tiller-namespace={{ .Values.helmOperator.tillerNamespace }}
        {{- if .Values.helmOperator.tls.enable }}
        - --tiller-tls-enable={{ .Values.helmOperator.tls.enable }}
        - --tiller-tls-key-path=/etc/fluxd/helm/{{ .Values.helmOperator.tls.keyFile }}
        - --tiller-tls-cert-path=/etc/fluxd/helm/{{ .Values.helmOperator.tls.certFile }}
        {{- if .Values.helmOperator.tls.verify }}
        - --tiller-tls-verify={{ .Values.helmOperator.tls.verify }}
        - --tiller-tls-ca-cert-path=/etc/fluxd/helm-ca/ca.crt
        {{- if .Values.helmOperator.tls.hostname }}
        - --tiller-tls-hostname={{ .Values.helmOperator.tls.hostname }}
        {{- end }}
        {{- end }}
        {{- end }}
      {{- if .Values.helmOperator.extraEnvs }}
        env:
{{ toYaml .Values.helmOperator.extraEnvs | indent 8 }}
      {{- end }}
        resources:
{{ toYaml .Values.helmOperator.resources | indent 10 }}
      {{- with .Values.helmOperator.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.helmOperator.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.helmOperator.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end -}}
