{{- $gitURL := default .Values.git.url .Values.helmOperator.git.url }}
{{- $gitBranch := default .Values.git.branch .Values.helmOperator.git.branch }}
{{- $gitPollInterval := default .Values.git.pollInterval .Values.helmOperator.git.pollInterval }}
{{- if .Values.helmOperator.create -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "flux.fullname" . }}-helm-operator
  labels:
    app: {{ template "flux.name" . }}-helm-operator
    chart: {{ template "flux.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "flux.name" . }}-helm-operator
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "flux.name" . }}-helm-operator
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ template "flux.serviceAccountName" . }}
      {{- end }}
      volumes:
      - name: sshdir
        configMap:
          name: {{ template "flux.fullname" . }}-ssh-config
          defaultMode: 0600
      - name: git-key
        secret:
          {{- if .Values.helmOperator.git.secretName }}
          secretName: {{ .Values.helmOperator.git.secretName }}
          {{- else }}
          secretName: {{ template "flux.fullname" . }}-git-deploy
          {{- end }}
          defaultMode: 0400
      {{- if .Values.helmOperator.tls.enable }}
      - name: helm-tls-certs
        secret:
          secretName: {{ .Values.helmOperator.tls.secretName }}
          defaultMode: 0400
      {{- if .Values.helmOperator.tls.verify }}
      - name: helm-tls-ca
        configMap:
          name: {{ template "flux.fullname" . }}-helm-tls-ca-config
          defaultMode: 0600
      {{- end }}
      {{- end }}
      containers:
      - name: flux-helm-operator
        image: "{{ .Values.helmOperator.repository }}:{{ .Values.helmOperator.tag }}"
        imagePullPolicy: {{ .Values.helmOperator.pullPolicy }}
        volumeMounts:
        - name: sshdir
          mountPath: /root/.ssh/known_hosts
          subPath: known_hosts
          readOnly: true
        - name: git-key
          mountPath: /etc/fluxd/ssh
          readOnly: true
        {{- if .Values.helmOperator.tls.enable }}
        - name: helm-tls-certs
          mountPath: /etc/fluxd/helm
          readOnly: true
        {{- if .Values.helmOperator.tls.verify }}
        - name: helm-tls-ca
          mountPath: /etc/fluxd/helm-ca
          readOnly: true
        {{- end }}
        {{- end }}
        args:
        - --git-url={{ $gitURL }}
        - --git-branch={{ $gitBranch }}
        - --git-poll-interval={{ $gitPollInterval }}
        - --git-charts-path={{ .Values.helmOperator.git.chartsPath }}
        - --charts-sync-interval={{ .Values.helmOperator.chartsSyncInterval }}
        - --charts-sync-timeout={{ .Values.helmOperator.chartsSyncTimeout }}
        - --log-release-diffs={{ .Values.helmOperator.logReleaseDiffs }}
        - --tiller-namespace={{ .Values.helmOperator.tillerNamespace }}
        {{- if .Values.helmOperator.tls.enable }}
        - --tiller-tls-enable={{ .Values.helmOperator.tls.enable }}
        - --tiller-tls-key-path=/etc/fluxd/helm/{{ .Values.helmOperator.tls.keyFile }}
        - --tiller-tls-cert-path=/etc/fluxd/helm/{{ .Values.helmOperator.tls.certFile }}
        {{- if .Values.helmOperator.tls.verify }}
        - --tiller-tls-verify={{ .Values.helmOperator.tls.verify }}
        - --tiller-tls-ca-cert-path=/etc/fluxd/helm-ca/ca.crt
        {{- end }}
        {{- end }}
{{- end -}}
