apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-helm-operator
  namespace: weave
  labels:
    app: flux-helm-operator
    weave-cloud-component: helm-operator
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flux-helm-operator
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "false"
      labels:
        app: flux-helm-operator
    spec:
      serviceAccountName: weave-flux
      volumes:
        - name: git-key
          secret:
            defaultMode: 256
            secretName: flux-git-deploy
      containers:
        - name: flux-helm-operator
          image: quay.io/weaveworks/helm-operator:0.5.3
          imagePullPolicy: IfNotPresent
          args:
            - --git-timeout=20s
            - --charts-sync-interval=3m
            - --update-chart-deps=true
            - --tiller-namespace=kube-system
          volumeMounts:
            - name: git-key
              mountPath: /etc/fluxd/ssh
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 64Mi
