version: 2
jobs:
  build:
    working_directory: /go/src/github.com/weaveworks/flux
    docker:
      - image: circleci/golang:1.10
      - image: memcached
    steps:
      - checkout
      - setup_remote_docker

      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure -vendor-only
      - run: make check-generated
      - run: make test TEST_FLAGS="-race -tags integration -timeout 60s"
      - run: make all

      - deploy:
          name: Maybe push master image
          command: |
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" quay.io
              docker push "quay.io/weaveworks/flux:$(docker/image-tag)"
              docker push "quay.io/weaveworks/helm-operator:$(docker/image-tag)"
            fi

      - deploy:
          name: Maybe push release image and upload binaries
          command: |
            if echo "${CIRCLE_TAG}" | grep -Eq "^[0-9]+(\.[0-9]+)*(-[a-z]+)?$"; then
              go get github.com/weaveworks/github-release
              make release-bins
              bin/upload-binaries
              docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" quay.io
              docker push "quay.io/weaveworks/flux:${CIRCLE_TAG}"
            fi
            if echo "${CIRCLE_TAG}" | grep -Eq "helm-[0-9]+(\.[0-9]+)*(-[a-z]+)?$"; then
              docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" quay.io
              RELEASE_TAG=$(echo "$CIRCLE_TAG" | cut -c 6-)
              docker push "quay.io/weaveworks/helm-operator:${RELEASE_TAG}"
            fi

workflows:
  version: 2
  build-and-push:
    jobs:
      - build:
          filters:
            tags:
              only: /(helm-)?[0-9]+(\.[0-9]+)*(-[a-z]+)?/
