version: 2
jobs:
  build:
    working_directory: /go/src/github.com/weaveworks/flux
    docker:
      - image: circleci/golang:1.10
      - image: memcached
    steps:
      - checkout
      - setup_remote_docker

      - run:
          # Ensure latest version of git
          command: |
            echo "deb http://deb.debian.org/debian stretch-backports main" | sudo tee -a /etc/apt/sources.list.d/stretch-backports.list
            sudo apt-get update
            sudo apt-get install -t stretch-backports -y --only-upgrade git
            git version
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure -vendor-only
      - run: make check-generated
      - run: make test TEST_FLAGS="-race -tags integration -timeout 60s"
      - run: make all

      - deploy:
          name: Maybe push prerelease images
          command: |
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              echo "$DOCKER_REGISTRY_PASSWORD" | docker login --username "$DOCKER_REGISTRY_USER" --password-stdin

              docker tag "docker.io/weaveworks/flux:$(docker/image-tag)" "docker.io/weaveworks/flux-prerelease:$(docker/image-tag)"
              docker push "docker.io/weaveworks/flux-prerelease:$(docker/image-tag)"

              docker tag "docker.io/weaveworks/helm-operator:$(docker/image-tag)" "docker.io/weaveworks/helm-operator-prerelease:$(docker/image-tag)"
              docker push "docker.io/weaveworks/helm-operator-prerelease:$(docker/image-tag)"
            fi

      - deploy:
          name: Maybe push release image and upload binaries
          command: |
            if echo "${CIRCLE_TAG}" | grep -Eq "^[0-9]+(\.[0-9]+)*(-[a-z]+)?$"; then
              go get github.com/weaveworks/github-release
              make release-bins
              bin/upload-binaries
              echo "$DOCKER_REGISTRY_PASSWORD" | docker login --username "$DOCKER_REGISTRY_USER" --password-stdin
              docker push "docker.io/weaveworks/flux:${CIRCLE_TAG}"
            fi
            if echo "${CIRCLE_TAG}" | grep -Eq "helm-[0-9]+(\.[0-9]+)*(-[a-z]+)?$"; then
              echo "$DOCKER_REGISTRY_PASSWORD" | docker login --username "$DOCKER_REGISTRY_USER" --password-stdin
              RELEASE_TAG=$(echo "$CIRCLE_TAG" | cut -c 6-)
              docker push "docker.io/weaveworks/helm-operator:${RELEASE_TAG}"
            fi
  e2e-testing:
    machine: true
    working_directory: ~/go/src/github.com/weaveworks/flux
    steps:
      - checkout
      - run: test/e2e/e2e-golang.sh
      - run: test/e2e/e2e-flux-build.sh
      - run: test/e2e/e2e-kind.sh
      - run: test/e2e/e2e-helm.sh
      - run: test/e2e/e2e-git.sh
      - run: test/e2e/e2e-flux-chart.sh

workflows:
  version: 2
  build-and-push:
    jobs:
      - build:
          filters:
            tags:
              only: /(helm-)?[0-9]+(\.[0-9]+)*(-[a-z]+)?/
      - e2e-testing:
          requires:
            - build
