---
# You can optionally deploy memcache, for the Flux daemon to cache
# container image metadata.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: memcached
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: memcached
    spec:
      containers:
      - name: memcached
        image: memcached:1.4.25
        imagePullPolicy: IfNotPresent
        args:
        - -m 64    # Maximum memory to use, in megabytes. 64MB is default.
        - -p 11211    # Default port, but being explicit is nice.
        - -vv    # This gets us to the level of request logs.
        ports:
        - name: clients
          containerPort: 11211
