apiVersion: v1
appVersion: "1.9.0"
version: 0.6.0
kubeVersion: ">=1.9.0-0"
name: flux
description: Flux is a tool that automatically ensures that the state of a cluster matches what is specified in version control
home: https://weave.works
sources:
- https://github.com/weaveworks/flux
maintainers:
  - name: stefanprodan
    email: stefan@weave.works
engine: gotpl
icon: https://raw.githubusercontent.com/weaveworks/flux/master/site/images/weave-flux.png
keywords:
  - gitops
