apiVersion: v1
appVersion: "1.13.2"
version: 0.11.0
kubeVersion: ">=1.9.0-0"
name: flux
description: Flux is a tool that automatically ensures that the state of a cluster matches what is specified in version control
home: https://fluxcd.io
sources:
- https://github.com/fluxcd/flux
maintainers:
  - name: stefanprodan
    email: stefan@weave.works
engine: gotpl
icon: https://raw.githubusercontent.com/fluxcd/flux/master/site/images/weave-flux.png
keywords:
  - gitops
