apiVersion: v1
appVersion: "1.8.1"
description: Flux is a tool that automatically ensures that the state of a cluster matches what is specified in version control
name: flux
version: 0.5.3
home: https://weave.works
sources:
- https://github.com/weaveworks/flux
maintainers:
  - name: stefanprodan
    email: stefan@weave.works
engine: gotpl
icon: https://raw.githubusercontent.com/weaveworks/flux/master/site/images/weave-flux.png
