apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flux
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: flux
    spec:
      containers:
      - name: fluxd
        image: quay.io/weaveworks/fluxd:master-6cc08e4
        args:
        - --fluxsvc-address=ws://localhost:3030
      - name: fluxsvc
        image: quay.io/weaveworks/fluxsvc:master-6cc08e4
        imagePullPolicy: Never
        args:
        - --database-source=file://fluxy.db
