name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: niden/actions-memcached@v7
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Run tests
        run: make test TEST_FLAGS="-race -tags integration -timeout 5m"
      - name: Check codegen
        run: make check-generated
      - name: Build binaries
        run: make all
      - name: Prepare cache
        run: |
          cp "$(go env GOPATH)/bin/fluxctl" cache/fluxctl
          docker save -o cache/flux-latest.tar fluxcd/flux:latest
      - name: Upload cache
        uses: actions/upload-artifact@v1
        with:
          name: cache
          path: cache
  e2e-testing:
    runs-on: ubuntu-latest
    needs: unit-testing
    strategy:
      matrix:
        test: ['10_* 11_* 12_*', '13_* 14_*', '15_* 16_* 17_*', '20_* 21_* 22_*']
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1
          image: kindest/node:v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Download cache
        uses: actions/download-artifact@v1
        with:
          name: cache
      - name: Load cache
        run: |
          chmod +x cache/fluxctl
          sudo mv cache/fluxctl /usr/local/bin/fluxctl
          docker load --input cache/flux-latest.tar -q
          kind load docker-image fluxcd/flux:latest
      - name: Run tests
        run: |
          E2E_TESTS='${{ matrix.test }}' make e2e-gh
