name: cve-scan

on:
  schedule:
    # Every day at 8am
    - cron: '0 8 * * *'

jobs:
  scan-prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Get prerelease tag
        id: prerelease
        run: |
          TAG=$(curl -s https://registry.hub.docker.com/v2/repositories/fluxcd/flux-prerelease/tags/?page_size=1|jq -r .results[].name)
          IMAGE="fluxcd/flux-prerelease:$TAG"
          echo "::set-output name=image::$IMAGE"
      - name: Scan prerelease
        uses: docker://docker.io/aquasec/trivy:latest
        with:
          args: --cache-dir /var/lib/trivy --no-progress --exit-code 1 --severity MEDIUM,HIGH,CRITICAL ${{ steps.prerelease.outputs.image }}
  scan-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get release tag
        id: release
        run: |
          TAG=$(curl -s https://registry.hub.docker.com/v2/repositories/fluxcd/flux/tags/?page_size=1|jq -r .results[].name)
          IMAGE="fluxcd/flux:$TAG"
          echo "::set-output name=image::$IMAGE"
      - name: Scan release
        uses: docker://docker.io/aquasec/trivy:latest
        with:
          args: --cache-dir /var/lib/trivy --no-progress --exit-code 1 --severity MEDIUM,HIGH,CRITICAL ${{ steps.release.outputs.image }}